name: therapeutic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^3.7.0
  google_sign_in: ^5.4.1
  glassmorphism: ^3.0.0
  http: ^0.13.5
  flutter_html: ^2.2.1
  animated_bottom_navigation_bar: ^1.1.0
  kf_drawer: ^1.2.1
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  connectivity: ^3.0.6
  permission_handler: ^10.0.0
  images_picker: ^1.2.11
  image_picker: ^0.8.5+3
  lottie: ^1.4.3
  firebase_core: ^1.22.0
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^3.0.1
  get_storage: ^2.0.3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

